<DataFrame 다루기 - 결측치(누락값) 처리 1>

목적        | 메서드       | 의미
누락값 확인 | isna()       | 누락값 위치 확인
누락값 개수 | isna().sum() | 열별 누락값 개수
행 삭제    | dropna()      | 누락값이 있는 행 삭제
값 대체    | fillna()      | 누락값을 다른 값으로 대체
평균       | mean()        | 기본적으로 누락값 제외
합계       | sum()         | 기본적으로 누락값 제외
개수       | count()       | 누락값 제외한 데이터 개수

※ 삭제 및 대체 판단

- 결측치를 억지로 채워 넣으면 오히려 분석 모델이 추측에 의존하게 되어 결과가 심각하게 왜곡될 수 있으니 주의

- 삭제 권장 (50% 이상): 결측치가 해당 열의 50%를 넘는다면, 어떤 값으로 채워도 신뢰성이 부족해집니다. 
이럴 땐 해당 열 전체를 삭제하는 것이 합리적입니다.

- 대체 권장 (20~30%): 결측치가 20~30% 수준이라면 평균, 중앙값, 혹은 회귀 분석을 통한 대체법을 사용하여 
데이터를 살리는 것이 좋습니다.

- 행 삭제: 결측치 수가 극소수라면 해당 행만 삭제해도 분석 결과에 큰 무리가 없습니다.

※ 데이터프레임에도 시리즈 기능과 동일한 기능의 메서드들이 많다. 그리고 시리즈 메세드와 메서드 이름도 동일하다.

| **기능** | **Series** | **DataFrame** | 
| 결측치 확인 | `s.isna()` | `df.isna()` | 
| 결측치 개수 | `s.isna().sum()` | `df.isna().sum()` | 
| 결측치 제거 | `s.dropna()` | `df.dropna()` | 
| 결측치 대체 | `s.fillna(0)` | `df.fillna(0)` | 
| 정렬       | `s.sort_values()` | `df.sort_values()` | 
| 중복 제거   | `s.drop_duplicates()` | `df.drop_duplicates()` | 
| 통계        | `s.mean()` | `df.mean()` | 
| 누적 최댓값 | `s.cummax()` | `df.cummax()` | 
| 누적 합 | `s.cumsum()` | `df.cumsum()` | 
| 값 개수 | `s.value_counts()` | `df.value_counts()` | 
| 형 변환 | `s.astype()` | `df.astype()` | 
| apply() | 값/요소에 적용 | 행/열 단위 적용 가능 |

In [1]:
import pandas as pd


# 누락값 확인 isna() 또는 isnull()을 사용한다.
# None은 python에서 값이 없는 객체
# NaN은 numpy, pandas의 숫자데이터의 결측값(None을 입력해도 NaN으로 처리됨)

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None],
    "출석": [True, True, None, True, False]
}

df = pd.DataFrame(data)

print(df) # 데이터프레임은 객체타입은 None, 숫자타입은 NaN으로 처리

print(df.isna())
print(df.isnull())

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [5]:
# ※ 불값을 sum연산을 하면 True -> 1, False -> 0 으로 계산된다 
#-> sum()메서드를 이용하여 결측치 개수 확인하는 방법 -> 결측치가 3개 있음을 확인

df.isna()

      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [6]:
df.isna().sum()

이름    0
점수    2
출석    1
dtype: int64

In [7]:
# 하나의 열을 분리 후 시리즈 메서드 isna()를 사용해도 된다.

print(df["점수"].isna()) # 점수열의 시리즈메서드 isna()

0    False
1     True
2    False
3    False
4     True
Name: 점수, dtype: bool

In [8]:
# 조건식 사용

cond = df["점수"].isna() # [False, True, False, False, True] 시리즈 반환
print(df[cond]) # df[[False, True, False, False, True]] => True인 인덱스1, 4행 출력

# 한줄의 코드로 만들면
print(df[df["점수"].isna()]) # df[조건] -> 행반환

# cond가 True 이름만 출력 => loc[] 인덱스 사용
print(df.loc[cond, "이름"]) # df[조건] -> 행반환
print(df.loc[df["점수"].isna(), "이름"]) # df[조건] -> 행반환

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
1    이서연
4    정현우
Name: 이름, dtype: str
1    이서연
4    정현우
Name: 이름, dtype: str

In [9]:
# 누락값 개수 확인
df.isna().sum()
# 이름    0 → 누락값 0개
# 점수    2 → 누락값 2개
# 출석    1 → 누락값 1개

이름    0
점수    2
출석    1
dtype: int64

In [10]:
print(df.isna().any()) # 데이터프레임 열에 누락값이 하나라도 있으면 True
# 이름    False
# 점수     True
# 출석     True

print(df.isna().all()) # 데이터프레임 열이 모두 누락값이면 True
# 이름    False
# 점수    False
# 출석    False

이름    False
점수     True
출석     True
dtype: bool
이름    False
점수    False
출석    False
dtype: bool

In [11]:
# 누락값 처리
# 누락값 처리는 크게 삭제와 대체 → 삭제보다는 대체

# dropna() 누락값이 있는 행 삭제한 데이터프레임을 반환
df2 = df.dropna()
print(df2)

# 원본의 행은 삭제 안됨
print(df)

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True
    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [12]:
# 특정열의 누락값이 있는 행 삭제한 데이터프레임 반환
df2 = df.dropna(subset=["점수", "출석"])
print(df2)

df2 = df.dropna(subset=["점수"])
print(df2)

# subset=df.columns 기본값

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True
    이름    점수    출석
0  김민준  85.0  True
2  박지훈  90.0  None
3  최유진  75.0  True

In [13]:
# 선택열의 누락값을 특정 값으로 대체 후 데이터셋(시리즈, 데이터프레임)반환 → fillna()
print(df["점수"].fillna(0)) # 열.fillna() 시리즈메서드 fillna() → 시리즈 반환
print(df[["점수","출석"]].fillna(0)) # 데이터프레임 메서드 fillna() → 데이터프레임 반환

# 원본에 대입
df["점수"] = df["점수"].fillna(0)
df

0    85.0
1     0.0
2    90.0
3    75.0
4     0.0
Name: 점수, dtype: float64
     점수     출석
0  85.0   True
1   0.0   True
2  90.0      0
3  75.0   True
4   0.0  False

    이름    점수     출석
0  김민준  85.0   True
1  이서연   0.0   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   0.0  False

In [14]:
# 평균값으로 누락값 대체
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None]
}

df = pd.DataFrame(data)
df

    이름    점수
0  김민준  85.0
1  이서연   NaN
2  박지훈  90.0
3  최유진  75.0
4  정현우   NaN

In [15]:
mean_score = df["점수"].mean()
df["점수"] = df["점수"].fillna(mean_score)
print(df)

    이름         점수
0  김민준  85.000000
1  이서연  83.333333
2  박지훈  90.000000
3  최유진  75.000000
4  정현우  83.333333

In [16]:
# 중앙값으로 대체

import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None]
}

df = pd.DataFrame(data)

median_score = df["점수"].median()

df["점수"] = df["점수"].fillna(median_score)

print(df)

    이름    점수
0  김민준  85.0
1  이서연  85.0
2  박지훈  90.0
3  최유진  75.0
4  정현우  85.0

In [17]:
# 범주(Category)의 경우 최빈값 대체

import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "성별": ["M", "F", None, "F", None] 
}

df = pd.DataFrame(data)

# mode()의 반환타입은 시리즈 타입이다. 결과값을 값을 가져오기 위해 위치값 [0]이 필요
mode_gender = df["성별"].mode()[0]

df["성별"] = df["성별"].fillna(mode_gender)

print(df)

    이름 성별
0  김민준  M
1  이서연  F
2  박지훈  F
3  최유진  F
4  정현우  F

In [18]:
# 통계(집계) 연산시 누락값이 포함되어 있는 경우
# 판다스의 주요 통계 함수는 기본적으로 누락값을 제외하고 계산한다.

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [80, None, 90, 70, None]
}

df = pd.DataFrame(data)


print("평균:", df["점수"].mean())
print("합계:", df["점수"].sum())
print("최댓값:", df["점수"].max())
print("최솟값:", df["점수"].min())

print("개수:",df["점수"].count())

평균: 80.0
합계: 240.0
최댓값: 90.0
최솟값: 70.0
개수: 3